### PR TITLE
fix: return 400 if uri is bad

### LINKED ISSUE #68: Handle invalid URIs
We've had a few events in our error monitoring due to an automatic scanner checking for log4j vulnerabilities using `X-Forwarded-For`:

```
❯ curl -ikH 'X-Forwarded-Host: [${jndi:ldap://172.16.26.190:52314/nessus}]/' example.com
HTTP/2 500
date: Tue, 12 Mar 2024 19:37:44 GMT
content-length: 77
server: nginx

An unhandled lowlevel error occurred. The application logs may have details.
```

This happens because this `request_uri` does not handle the URI being invalid:

https://github.com/tylerhunt/rack-canonical-host/blob/134f76f90d73f577b4359360f8be4f138e1e08b0/lib/rack/canonical_host/redirect.rb#L86-L88

I think instead what should probably happen is that the error is caught and the request considered _not_ canonical (thus triggering a redirect) since implicitly the canonical URL must be a valid URI so whatever the requests current url is cannot be canonical.

I'm happy to have a go at a PR for this if folks agree it should be addressed here

### PR DESCRIPTION
**Pull request by G-Rath**
I still think it could be possible to redirect these, but ultimately a bad uri is a sign that something weird is going on that is probably an edge case so it should be perfectly fine to just return a 400.

Resolves #68
Closes #64

### CODE REVIEW

File: lib/rack/canonical_host.rb [hunk 1]
```diff
@@ -15,11 +15,13 @@ def call(env)
...
       redirect = Redirect.new(env, host, options)
 
-      if redirect.canonical?
-        app.call(env)
-      else
-        redirect.response
+      begin
+        return redirect.response unless redirect.canonical?
+      rescue Addressable::URI::InvalidURIError
+        return [400, { Rack::CONTENT_TYPE => "text/plain", Rack::CONTENT_LENGTH => "0" }, []]
```
Comment (G-Rath) [inline lib/rack/canonical_host.rb:21]: this is based on what Rack uses internally:

https://github.com/rack/rack/blob/dff6cfd249832d32ab190e6d20605bce0d6c702d/lib/rack/auth/abstract/handler.rb#L31-L37
